# -*- coding: utf-8 -*-
import json
import re

all_translations = {
    "kn": {
        "dpdpAct": "DPDP ಕಾಯ್ದೆ",
        "signIn": "ಸೈನ್ ಇನ್",
        "createAccount": "ಖಾತೆ ರಚಿಸಿ",
        "digitalCitizenWelfare": "ಡಿಜಿಟಲ್ ನಾಗರಿಕ ಕಲ್ಯಾಣ ವೇದಿಕೆ",
        "govTechSandbox": "ಸರ್ಕಾರಿ ತಂತ್ರಜ್ಞಾನ ಸ್ಯಾಂಡ್‌ಬಾಕ್ಸ್: ಸಕ್ರಿಯ",
        "deterministic": "ನಿಖರ ಗಣಿತೀಯ ಫಲಿತಾಂಶ",
        "highContrastMode": "ಹೆಚ್ಚಿನ ಕಾಂಟ್ರಾಸ್ಟ್",
        "simpleModeLabel": "ಸರಳ ಮೋಡ್",
        "footerTagline": "ಸಾರ್ವಜನಿಕ ಸೇವಾ ಕಲ್ಯಾಣ ವೇದಿಕೆ",
        "footerDesc": "ಭಾರತದಾದ್ಯಂತ ನಾಗರಿಕರಿಗೆ ಗೌಪ್ಯತೆ-ರಕ್ಷಣೆಯೊಂದಿಗೆ ಸರ್ಕಾರಿ ಕಲ್ಯಾಣ ಯೋಜನೆಗಳ ಪ್ರವೇಶವನ್ನು ಒದಗಿಸುತ್ತದೆ. DPDP ಕಾಯ್ದೆಯ ಅಡಿಯಲ್ಲಿ ಡಿಜಿಟಲ್ ವಿಶ್ವಾಸಾರ್ಹತೆ ಮತ್ತು ಸೈಬರ್ ಭದ್ರತೆಯನ್ನು ಬೆಂಬಲಿಸಲು ವಿನ್ಯಾಸಗೊಳಿಸಲಾಗಿದೆ.",
        "headquarters": "ಪ್ರಧಾನ ಕಚೇರಿ: ರಾಷ್ಟ್ರೀಯ ಮಾಹಿತಿ ಕೇಂದ್ರ (NIC) ಮತ್ತು ನಾಗರಿಕ ಸಹಾಯ ಕೇಂದ್ರ, ಬೆಂಗಳೂರು, ಕರ್ನಾಟಕ, ಭಾರತ",
        "emailSupportLabel": "ಇಮೇಲ್ ಬೆಂಬಲ:",
        "getSchemeNotifications": "ಯೋಜನೆ ಮತ್ತು ನವೀಕರಣ ಅಧಿಸೂಚನೆಗಳನ್ನು ಪಡೆಯಿರಿ",
        "notifyMe": "ನನಗೆ ತಿಳಿಸಿ",
        "zeroSpamGuarantee": "ಶೂನ್ಯ ಸ್ಪ್ಯಾಮ್ ಭರವಸೆ. 100% ಸಮ್ಮತಿ ಆಧಾರಿತ DPDP ಅನುಸರಣೆ.",
        "enterEmailToNotify": "ಅಧಿಕೃತ ಅಪ್‌ಡೇಟ್‌ಗಳಿಗಾಗಿ ನಿಮ್ಮ ಇಮೇಲ್ ನಮೂದಿಸಿ",
        "citizenServices": "ನಾಗರಿಕ ಸೇವೆಗಳು",
        "product": "ಉತ್ಪನ್ನ ವೈಶಿಷ್ಟ್ಯಗಳು",
        "trustAndCompliance": "ವಿಶ್ವಾಸ ಮತ್ತು ನಿಯಮ ಪಾಲನೆ",
        "yourChoices": "ನಿಮ್ಮ ಆಯ್ಕೆಗಳು",
        "manageCookiePreferences": "ಕುಕಿ ಪ್ರಾಶಸ್ತ್ಯಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
        "consentFramework": "ಸಮ್ಮತಿ ಚೌಕಟ್ಟು",
        "cookiePolicy": "ಕುಕಿ ನೀತಿ",
        "privacyPolicy": "ಗೌಪ್ಯತಾ ನೀತಿ",
        "accessibility": "ಪ್ರವೇಶಿಸುವಿಕೆ",
        "dpdpCompliance": "DPDP ಅನುಸರಣೆ",
        "eligibilityChecker": "ಅರ್ಹತಾ ಪರಿಶೀಲಕ",
        "welfareGapsReport": "ಕಲ್ಯಾಣ ಕೊರತೆಗಳ ವರದಿ",
        "digilockerVerification": "ಡಿಜಿಲಾಕರ್ ಪರಿಶೀಲನೆ",
        "whatIfSimulation": "ಸಾಂದರ್ಭಿಕ ಸಿಮ್ಯುಲೇಶನ್",
        "interactiveRoadmap": "ಸಂವಾದಾತ್ಮಕ ಮಾರ್ಗಸೂಚಿ",
        "citizenPortal": "ನಾಗರಿಕ ಪೋರ್ಟಲ್",
        "welcomeToSahaya": "ಟೆಕ್ ಸಹಾಯಕ್ಕೆ ಸುಸ್ವಾಗತ",
        "welcomePortalDesc": "ವೈಯಕ್ತಿಕಗೊಳಿಸಿದ ಕಲ್ಯಾಣ ಯೋಜನೆಗಳು, ದಾಖಲೆಗಳ ವಾಲ್ಟ್ ಮತ್ತು ನೈಜ-ಸಮಯದ ಅರ್ಹತೆಗಾಗಿ ಸುರಕ್ಷಿತ ನಾಗರಿಕ ಪ್ರವೇಶ.",
        "secureCitizenAccess": "ಸುರಕ್ಷಿತ ನಾಗರಿಕ ಲಾಗಿನ್",
        "signInTitle": "ಟೆಕ್ ಸಹಾಯಕ್ಕೆ ಸೈನ್ ಇನ್ ಮಾಡಿ",
        "signInSubtitle": "ಪರಿಶೀಲಿಸಿದ ಕಲ್ಯಾಣ ಯೋಜನೆಗಳು ಮತ್ತು ದಾಖಲೆಗಳನ್ನು ಪ್ರವೇಶಿಸಲು ನಿಮ್ಮ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ.",
        "emailAddressLabel": "ಇಮೇಲ್ ವಿಳಾಸ",
        "passwordLabel": "ಪಾಸ್‌ವರ್ಡ್",
        "rememberMe": "ನನ್ನನ್ನು ನೆನಪಿಡಿ",
        "forgotPasswordLink": "ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರಾ?",
        "continueToVerification": "ದ್ವಿ-ಹಂತದ ಪರಿಶೀಲನೆಗೆ ಮುಂದುವರಿಯಿರಿ",
        "verifyingSending": "ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ ಮತ್ತು ಕೋಡ್ ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ...",
        "cybersecurityGate": "ಸೈಬರ್ ಭದ್ರತಾ ಸಮಗ್ರತೆ ಗೇಟ್",
        "twoStepVerification": "ದ್ವಿ-ಹಂತದ ಪರಿಶೀಲನೆ",
        "sentSecurityCode": "ನಾವು 6-ಅಂಕಿಯ ಭದ್ರತಾ ಕೋಡ್ ಕಳುಹಿಸಿದ್ದೇವೆ:",
        "enter6DigitCode": "6-ಅಂಕಿಯ ಕೋಡ್ ನಮೂದಿಸಿ",
        "didntReceiveCode": "ಕೋಡ್ ಬಂದಿಲ್ಲವೇ?",
        "resendOtp": "ಮತ್ತೆ ಕೋಡ್ ಕಳುಹಿಸಿ (Resend OTP)",
        "verifyAndSignIn": "ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಸೈನ್ ಇನ್ ಮಾಡಿ",
        "verifying": "ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...",
        "backToLogin": "← ಲಾಗಿನ್‌ಗೆ ಹಿಂತಿರುಗಿ",
        "dontHaveAccount": "ಖಾತೆ ಇಲ್ಲವೇ?",
        "createAccountLink": "ಖಾತೆ ರಚಿಸಿ",
        "autoFillCode": "ಕೋಡ್ ಭರ್ತಿ ಮಾಡಿ",
        "securityCodeNotice": "ನಿಮ್ಮ 6-ಅಂಕಿಯ ಪರಿಶೀಲನಾ ಕೋಡ್:",
        "securityCodeSent": "ಅಧಿಕೃತ ಭದ್ರತಾ ಕೋಡ್ ಕಳುಹಿಸಲಾಗಿದೆ"
    },
    "te": {
        "dpdpAct": "DPDP చట్టం",
        "signIn": "సైన్ ఇన్",
        "createAccount": "ఖాతా సృష్టించండి",
        "digitalCitizenWelfare": "డిజిటల్ పౌర సంక్షేమ వేదిక",
        "govTechSandbox": "ప్రభుత్వ టెక్ సాండ్‌బాక్స్: ప్రత్యక్షం",
        "deterministic": "కచ్చితమైన గణితీయ ఫలితాలు",
        "highContrastMode": "హై కాంట్రాస్ట్",
        "simpleModeLabel": "సరళ మోడ్",
        "footerTagline": "ప్రజా సేవా సంక్షేమ వేదిక",
        "footerDesc": "భారతదేశం అంతటా పౌరులకు గోప్యతా రక్షణతో ప్రభుత్వ సంక్షేమ పథకాలకు ప్రాప్యతను అందిస్తుంది. DPDP చట్టం కింద డిజిటల్ విశ్వాసం మరియు సైబర్ భద్రతను నిర్ధారిస్తుంది.",
        "headquarters": "ప్రధాన కార్యాలయం: నేషనల్ ఇన్ఫర్మేటిక్స్ సెంటర్ (NIC) & పౌర సహాయ కేంద్రం, బెంగళూరు, భారతదేశం",
        "emailSupportLabel": "ఇమెయిల్ మద్దతు:",
        "getSchemeNotifications": "పథకం మరియు పునరుద్ధరణ నోటిఫికేషన్‌లను పొందండి",
        "notifyMe": "నాకు తెలియజేయండి",
        "zeroSpamGuarantee": "జీరో స్పామ్ హామీ. 100% సమ్మతి ఆధారిత DPDP వర్తింపు.",
        "enterEmailToNotify": "అధికారిక అప్‌డేట్‌ల కోసం మీ ఇమెయిల్‌ను నమోదు చేయండి",
        "citizenServices": "పౌర సేవలు",
        "product": "ఉత్పత్తి ఫీచర్లు",
        "trustAndCompliance": "విశ్వాసం & నిబంధనల పాటించటం",
        "yourChoices": "మీ ఎంపికలు",
        "manageCookiePreferences": "కుకీ ప్రాధాన్యతలను నిర్వహించండి",
        "consentFramework": "సమ్మతి ఫ్రేమ్‌వర్క్",
        "cookiePolicy": "కుకీ విధానం",
        "privacyPolicy": "గోప్యతా విధానం",
        "accessibility": "ప్రాప్యత (Accessibility)",
        "dpdpCompliance": "DPDP వర్తింపు",
        "eligibilityChecker": "అర్హత తనిఖీ",
        "welfareGapsReport": "సంక్షేమ లోపాల నివేదిక",
        "digilockerVerification": "డిజిలాకర్ ధృవీకరణ",
        "whatIfSimulation": "సిమ్యులేషన్ విశ్లేషణ",
        "interactiveRoadmap": "ఇంటరాక్టివ్ రోడ్‌మ్యాప్",
        "citizenPortal": "పౌర పోర్టల్",
        "welcomeToSahaya": "టెక్ సహాయకు స్వాగతం",
        "welcomePortalDesc": "వ్యక్తిగతీకరించిన సంక్షేమ పథకాలు, పత్రాల వాల్ట్ మరియు నిజ-సమయ అర్హత ట్రాకింగ్ కోసం సురక్షిత పౌర ప్రాప్యత.",
        "secureCitizenAccess": "సురక్షిత పౌర లాగిన్",
        "signInTitle": "టెక్ సహాయకు సైన్ ఇన్ చేయండి",
        "signInSubtitle": "ధృవీకరించబడిన సంక్షేమ ప్రయోజనాలు మరియు పత్రాలను పొందడానికి మీ వివరాలను నమోదు చేయండి.",
        "emailAddressLabel": "ఇమెయిల్ చిరునామా",
        "passwordLabel": "పాస్‌వర్డ్",
        "rememberMe": "నన్ను గుర్తుంచుకో",
        "forgotPasswordLink": "పాస్‌వర్డ్ మర్చిపోయారా?",
        "continueToVerification": "ద్వి-దశల ధృవీకరణకు కొనసాగించండి",
        "verifyingSending": "ధృవీకరిస్తోంది & కోడ్ పంపబడుతోంది...",
        "cybersecurityGate": "సైబర్ సెక్యూరిటీ సమగ్రత గేట్",
        "twoStepVerification": "రెండు-దశల ధృవీకరణ (2FA)",
        "sentSecurityCode": "మేము 6-అంకెల భద్రతా కోడ్‌ను పంపాము:",
        "enter6DigitCode": "6-అంకెల కోడ్‌ను నమోదు చేయండి",
        "didntReceiveCode": "కోడ్ రాలేదా?",
        "resendOtp": "మళ్ళీ పంపండి (Resend OTP)",
        "verifyAndSignIn": "ధృవీకరించి సైన్ ఇన్ అవ్వండి",
        "verifying": "ధృవీకరిస్తోంది...",
        "backToLogin": "← లాగిన్‌కు తిరిగి వెళ్ళు",
        "dontHaveAccount": "ఖాతా లేదా?",
        "createAccountLink": "ఖాతా సృష్టించండి",
        "autoFillCode": "కోడ్ నింపండి",
        "securityCodeNotice": "మీ 6-అంకెల ధృవీకరణ కోడ్:",
        "securityCodeSent": "అధికారిక భద్రతా కోడ్ పంపబడింది"
    },
    "ta": {
        "dpdpAct": "DPDP சட்டம்",
        "signIn": "உள்நுழைக",
        "createAccount": "கணக்கை உருவாக்குக",
        "digitalCitizenWelfare": "டிஜிட்டல் குடிமக்கள் நல மேடை",
        "govTechSandbox": "அரசு தொழில்நுட்ப சாண்ட்பாக்ஸ்: நேரலை",
        "deterministic": "துல்லிய கணித முடிவுகள்",
        "highContrastMode": "அதிக மாறுபாடு (High Contrast)",
        "simpleModeLabel": "எளிய முறை",
        "footerTagline": "பொது சேவை நலத்திட்ட தளம்",
        "footerDesc": "இந்தியா முழுவதும் உள்ள குடிமக்களுக்கு தனியுரிமை பாதுகாப்புடன் அரசு நலத்திட்டங்களை அணுக உதவுகிறது. DPDP சட்டத்தின் கீழ் டிஜிட்டல் நம்பிக்கை மற்றும் சைபர் பாதுகாப்பை உறுதி செய்கிறது.",
        "headquarters": "தலைமையகம்: தேசிய தகவலியல் மையம் (NIC) மற்றும் குடிமக்கள் உதவி மையம், பெங்களூரு, இந்தியா",
        "emailSupportLabel": "மின்னஞ்சல் ஆதரவு:",
        "getSchemeNotifications": "திட்டம் மற்றும் புதுப்பித்தல் அறிவிப்புகளைப் பெறுங்கள்",
        "notifyMe": "எனக்கு அறிவிக்கவும்",
        "zeroSpamGuarantee": "ஸ்பேம் இல்லாத உத்தரவாதம். 100% ஒப்புதல் அடிப்படையிலான DPDP இணக்கம்.",
        "enterEmailToNotify": "அதிகாரப்பூர்வ அறிவிப்புகளுக்கு மின்னஞ்சலை உள்ளிடவும்",
        "citizenServices": "குடிமக்கள் சேவைகள்",
        "product": "தயாரிப்பு அம்சங்கள்",
        "trustAndCompliance": "நம்பிக்கை & சட்ட இணக்கம்",
        "yourChoices": "உங்கள் தேர்வுகள்",
        "manageCookiePreferences": "குக்கீ விருப்பங்களை நிர்வகிக்கவும்",
        "consentFramework": "ஒப்புதல் கட்டமைப்பு",
        "cookiePolicy": "குக்கீ கொள்கை",
        "privacyPolicy": "தனியுரிமைக் கொள்கை",
        "accessibility": "அணுகல்தன்மை (Accessibility)",
        "dpdpCompliance": "DPDP இணக்கம்",
        "eligibilityChecker": "தகுதி சரிபார்ப்பான்",
        "welfareGapsReport": "விடுபட்ட பலன்கள் அறிக்கை",
        "digilockerVerification": "டிஜிலாக்கர் சரிபார்ப்பு",
        "whatIfSimulation": "மாதிரி உருவகப்படுத்துதல்",
        "interactiveRoadmap": "ஊடாடும் வழிகாட்டி",
        "citizenPortal": "குடிமக்கள் போர்டல்",
        "welcomeToSahaya": "டெக் சகாயாவிற்கு நல்வரவு",
        "welcomePortalDesc": "தனிப்பயனாக்கப்பட்ட நலத்திட்டங்கள், ஆவண பெட்டகம் மற்றும் நேரடி தகுதி கண்காணிப்புக்கான பாதுகாப்பான தளம்.",
        "secureCitizenAccess": "பாதுகாப்பான குடிமக்கள் உள்நுழைவு",
        "signInTitle": "டெக் சகாயாவில் உள்நுழைக",
        "signInSubtitle": "சரிபார்க்கப்பட்ட நலத்திட்டங்கள் மற்றும் ஆவணங்களை அணுக உங்கள் விவரங்களை உள்ளிடவும்.",
        "emailAddressLabel": "மின்னஞ்சல் முகவரி",
        "passwordLabel": "கடவுச்சொல்",
        "rememberMe": "என்னை நினைவில் கொள்க",
        "forgotPasswordLink": "கடவுச்சொல் மறந்துவிட்டதா?",
        "continueToVerification": "இரண்டு-படி சரிபார்ப்பிற்கு தொடரவும்",
        "verifyingSending": "சரிபார்க்கப்பட்டு குறியீடு அனுப்பப்படுகிறது...",
        "cybersecurityGate": "சைபர் பாதுகாப்பு நம்பகத்தன்மை வாயில்",
        "twoStepVerification": "இரண்டு-படி சரிபார்ப்பு (2FA)",
        "sentSecurityCode": "6-இலக்க பாதுகாப்பு குறியீட்டை அனுப்பியுள்ளோம்:",
        "enter6DigitCode": "6-இலக்க குறியீட்டை உள்ளிடவும்",
        "didntReceiveCode": "குறியீடு வரவில்லையா?",
        "resendOtp": "மீண்டும் அனுப்பு (Resend OTP)",
        "verifyAndSignIn": "சரிபார்த்து உள்நுழைக",
        "verifying": "சரிபார்க்கிறது...",
        "backToLogin": "← உள்நுழைவுக்கு திரும்புக",
        "dontHaveAccount": "கணக்கு இல்லையா?",
        "createAccountLink": "கணக்கை உருவாக்குக",
        "autoFillCode": "குறியீட்டை நிரப்புக",
        "securityCodeNotice": "உங்கள் 6-இலக்க சரிபார்ப்புக் குறியீடு:",
        "securityCodeSent": "அதிகாரப்பூர்வ பாதுகாப்பு குறியீடு அனுப்பப்பட்டது"
    },
    "ml": {
        "dpdpAct": "DPDP നിയമം",
        "signIn": "സൈൻ ഇൻ ചെയ്യുക",
        "createAccount": "അക്കൗണ്ട് ഉണ്ടാക്കുക",
        "digitalCitizenWelfare": "ഡിജിറ്റൽ പൗരക്ഷേമ വേദി",
        "govTechSandbox": "ഗവ ടെക് സാൻഡ്‌ബോക്സ്: സജീവം",
        "deterministic": "കൃത്യമായ ഗണിതശാസ്ത്ര ഫലങ്ങൾ",
        "highContrastMode": "ഹൈ കോൺട്രാസ്റ്റ്",
        "simpleModeLabel": "ലളിത മോഡ്",
        "footerTagline": "പൊതുജന സേവന ക്ഷേമ പ്ലാറ്റ്‌ഫോം",
        "footerDesc": "ഇന്ത്യയിലുടനീളമുള്ള പൗരന്മാർക്ക് പൂർണ്ണ വിവര സുരക്ഷിതത്വത്തോടെ സർക്കാർ ക്ഷേമ പദ്ധതികൾ പ്രാപ്യമാക്കുന്നു. DPDP നിയമപ്രകാരം ഡിജിറ്റൽ വിശ്വാസ്യതയും സൈബർ സുരക്ഷയും ഉറപ്പാക്കുന്നു.",
        "headquarters": "ആസ്ഥാനം: നാഷണൽ ഇൻഫോർമാറ്റിക്സ് സെന്റർ (NIC) & പൗര സഹായ കേന്ദ്രം, ബെംഗളൂരു, ഇന്ത്യ",
        "emailSupportLabel": "ഇമെയിൽ സഹായം:",
        "getSchemeNotifications": "പദ്ധതി അറിയിപ്പുകൾ നേടുക",
        "notifyMe": "എന്നെ അറിയിക്കുക",
        "zeroSpamGuarantee": "സ്പാം രഹിത സേവനം. 100% സമ്മതത്തിലധിഷ്ഠിതമായ DPDP സുരക്ഷ.",
        "enterEmailToNotify": "അറിയിപ്പുകൾക്കായി ഇമെയിൽ നൽകുക",
        "citizenServices": "പൗര സേവനങ്ങൾ",
        "product": "പ്രത്യേകതകൾ",
        "trustAndCompliance": "വിശ്വാസ്യതയും നിയമസാധുതയും",
        "yourChoices": "നിങ്ങളുടെ തിരഞ്ഞെടുപ്പുകൾ",
        "manageCookiePreferences": "കുക്കി ക്രമീകരണങ്ങൾ",
        "consentFramework": "സമ്മത ചട്ടക്കൂട്",
        "cookiePolicy": "കുക്കി നയം",
        "privacyPolicy": "സ്വകാര്യതാ നയം",
        "accessibility": "പ്രാപ്യത (Accessibility)",
        "dpdpCompliance": "DPDP അനുസരണം",
        "eligibilityChecker": "അർഹതാ പരിശോധന",
        "welfareGapsReport": "നഷ്ടമായ ആനുകൂല്യങ്ങളുടെ റിപ്പോർട്ട്",
        "digilockerVerification": "ഡിജിലോക്കർ പരിശോധന",
        "whatIfSimulation": "സിമുലേഷൻ പരിശോധന",
        "interactiveRoadmap": "വഴികാട്ടി റോഡ്‌മാപ്പ്",
        "citizenPortal": "പൗര പോർട്ടൽ",
        "welcomeToSahaya": "ടെക് സഹായയിലേക്ക് സ്വാഗതം",
        "welcomePortalDesc": "വ്യക്തിഗത ക്ഷേമ പദ്ധതികൾ, രേഖകളുടെ സുരക്ഷിത സൂക്ഷിപ്പ്, തത്സമയ അർഹതാ പരിശോധന എന്നിവയ്ക്കുള്ള സുരക്ഷിത പ്ലാറ്റ്‌ഫോം.",
        "secureCitizenAccess": "സുരക്ഷിത പൗര പ്രവേശനം",
        "signInTitle": "ടെക് സഹായയിൽ സൈൻ ഇൻ ചെയ്യുക",
        "signInSubtitle": "പരിശോധിച്ച ക്ഷേമ ആനുകൂല്യങ്ങളും രേഖകളും ലഭിക്കുന്നതിന് നിങ്ങളുടെ വിവരങ്ങൾ നൽകുക.",
        "emailAddressLabel": "ഇമെയിൽ വിലാസം",
        "passwordLabel": "പാസ്‌വേഡ്",
        "rememberMe": "ഓർത്തു വെക്കുക",
        "forgotPasswordLink": "പാസ്‌വേഡ് മറന്നോ?",
        "continueToVerification": "ദ്വിതല പരിശോധനയിലേക്ക് തുടരുക",
        "verifyingSending": "പരിശോധിക്കുകയും കോഡ് അയയ്ക്കുകയും ചെയ്യുന്നു...",
        "cybersecurityGate": "സൈബർ സുരക്ഷാ കവാടം",
        "twoStepVerification": "ദ്വിതല സുരക്ഷാ പരിശോധന (2FA)",
        "sentSecurityCode": "ഞങ്ങൾ 6 അക്ക സുരക്ഷാ കോഡ് അയച്ചിട്ടുണ്ട്:",
        "enter6DigitCode": "6 അക്ക കോഡ് നൽകുക",
        "didntReceiveCode": "കോഡ് ലഭിച്ചില്ലേ?",
        "resendOtp": "വീണ്ടും അയക്കുക (Resend OTP)",
        "verifyAndSignIn": "പരിശോധിച്ച് സൈൻ ഇൻ ചെയ്യുക",
        "verifying": "പരിശോധിക്കുന്നു...",
        "backToLogin": "← ലോഗിനിലേക്ക് മടങ്ങുക",
        "dontHaveAccount": "അക്കൗണ്ട് ഇല്ലേ?",
        "createAccountLink": "അക്കൗണ്ട് ഉണ്ടാക്കുക",
        "autoFillCode": "കോഡ് പൂരിപ്പിക്കുക",
        "securityCodeNotice": "നിങ്ങളുടെ 6 അക്ക പരിശോധനാ കോഡ്:",
        "securityCodeSent": "ഔദ്യോഗിക സുരക്ഷാ കോഡ് അയച്ചു"
    },
    "bn": {
        "dpdpAct": "DPDP আইন",
        "signIn": "সাইন ইন করুন",
        "createAccount": "অ্যাকাউন্ট তৈরি করুন",
        "digitalCitizenWelfare": "ডিজিটাল নাগরিক কল্যাণ প্ল্যাটফর্ম",
        "govTechSandbox": "সরকারি টেক স্যান্ডবক্স: লাইভ",
        "deterministic": "নিখুঁত গাণিতিক ফলাফল",
        "highContrastMode": "উচ্চ বৈসাদৃশ্য (High Contrast)",
        "simpleModeLabel": "সহজ মোড",
        "footerTagline": "জনসেবা কল্যাণমূলক প্ল্যাটফর্ম",
        "footerDesc": "ভারত জুড়ে নাগরিকদের গোপনীয়তা বজায় রেখে সরকারি কল্যাণমূলক প্রকল্পের সুযোগ প্রদান করে। DPDP আইনের অধীনে ডিজিটাল বিশ্বাস ও সাইবার নিরাপত্তা নিশ্চিত করে।",
        "headquarters": "সদর দপ্তর: জাতীয় তথ্যবিজ্ঞান কেন্দ্র (NIC) ও নাগরিক সহায়তা কেন্দ্র, বেঙ্গালুরু, ভারত",
        "emailSupportLabel": "ইমেল সহায়তা:",
        "getSchemeNotifications": "প্রকল্প ও নবায়ন সংক্রান্ত বিজ্ঞপ্তি পান",
        "notifyMe": "আমাকে জানান",
        "zeroSpamGuarantee": "স্প্যাম-মুক্ত পরিষেবা। ১০০% সম্মতি ভিত্তিক DPDP আইনসম্মত।",
        "enterEmailToNotify": "অফিসিয়াল আপডেটের জন্য আপনার ইমেল লিখুন",
        "citizenServices": "নাগরিক সেবাসমূহ",
        "product": "বৈশিষ্ট্যসমূহ",
        "trustAndCompliance": "বিশ্বাস ও আইনি সম্মতি",
        "yourChoices": "আপনার পছন্দসমূহ",
        "manageCookiePreferences": "কুকি পছন্দ পরিচালনা করুন",
        "consentFramework": "সম্মতি কাঠামো",
        "cookiePolicy": "কুকি নীতি",
        "privacyPolicy": "গোপনীয়তা নীতি",
        "accessibility": "প্রবেশযোগ্যতা (Accessibility)",
        "dpdpCompliance": "DPDP সম্মতি",
        "eligibilityChecker": "যোগ্যতা পরীক্ষক",
        "welfareGapsReport": "কল্যাণমূলক ফাঁক সংক্রান্ত রিপোর্ট",
        "digilockerVerification": "ডিজিলকার যাচাইকরণ",
        "whatIfSimulation": "সিমুলেশন বিশ্লেষণ",
        "interactiveRoadmap": "ইন্টারেক্টিভ রোডম্যাপ",
        "citizenPortal": "নাগরিক পোর্টাল",
        "welcomeToSahaya": "টেক সহায়ে স্বাগতম",
        "welcomePortalDesc": "ব্যক্তিগতকৃত কল্যাণ প্রকল্প, নথিপত্র এবং বাস্তব সময় যোগ্যতা নিরীক্ষণের জন্য সুরক্ষিত নাগরিক প্রবেশদ্বার।",
        "secureCitizenAccess": "সুরক্ষিত নাগরিক লগইন",
        "signInTitle": "টেক সহায়ে সাইন ইন করুন",
        "signInSubtitle": "যাচাইকৃত সুবিধা ও নথিপত্র অ্যাক্সেস করতে আপনার বিবরণ লিখুন।",
        "emailAddressLabel": "ইমেল ঠিকানা",
        "passwordLabel": "পাসওয়ার্ড",
        "rememberMe": "মনে রাখুন",
        "forgotPasswordLink": "পাসওয়ার্ড ভুলে গেছেন?",
        "continueToVerification": "দ্বি-পদক্ষেপ যাচাইকরণে এগিয়ে যান",
        "verifyingSending": "যাচাই করা হচ্ছে এবং কোড পাঠানো হচ্ছে...",
        "cybersecurityGate": "সাইবার নিরাপত্তা ইন্টিগ্রিটি গেট",
        "twoStepVerification": "দ্বি-পদক্ষেপ যাচাইকরণ (2FA)",
        "sentSecurityCode": "আমরা একটি ৬-সংখ্যার নিরাপত্তা কোড পাঠিয়েছি:",
        "enter6DigitCode": "৬-সংখ্যার কোড লিখুন",
        "didntReceiveCode": "কোড পাননি?",
        "resendOtp": "পুনরায় কোড পাঠান (Resend OTP)",
        "verifyAndSignIn": "যাচাই করুন এবং সাইন ইন করুন",
        "verifying": "যাচাই করা হচ্ছে...",
        "backToLogin": "← লগইনে ফিরে যান",
        "dontHaveAccount": "অ্যাকাউন্ট নেই?",
        "createAccountLink": "অ্যাকাউন্ট তৈরি করুন",
        "autoFillCode": "কোড পূরণ করুন",
        "securityCodeNotice": "আপনার ৬-সংখ্যার যাচাইকরণ কোড:",
        "securityCodeSent": "অফিসিয়াল নিরাপত্তা কোড পাঠানো হয়েছে"
    },
    "mr": {
        "dpdpAct": "DPDP कायदा",
        "signIn": "साइन इन करा",
        "createAccount": "खाते तयार करा",
        "digitalCitizenWelfare": "डिजिटल नागरिक कल्याण मंच",
        "govTechSandbox": "शासकीय टेक सँडबॉक्स: थेट",
        "deterministic": "अचूक गणितीय निकाल",
        "highContrastMode": "उच्च कॉन्ट्रास्ट (High Contrast)",
        "simpleModeLabel": "सोपा मोड",
        "footerTagline": "लोकसेवा कल्याण मंच",
        "footerDesc": "संपूर्ण भारतातील नागरिकांना गोपनीयतेचे रक्षण करून सरकारी योजनांचा लाभ मिळवून देतो. DPDP कायद्यांतर्गत डिजिटल विश्वास आणि सायबर सुरक्षा सुनिश्चित करतो.",
        "headquarters": "मुख्यालय: राष्ट्रीय माहिती विज्ञान केंद्र (NIC) आणि नागरिक मदत कक्ष, बेंगळुरू, भारत",
        "emailSupportLabel": "ईमेल मदत:",
        "getSchemeNotifications": "योजना आणि नूतनीकरण सूचना मिळवा",
        "notifyMe": "मला कळवा",
        "zeroSpamGuarantee": "शून्य स्पॅम हमी. १००% संमती आधारित DPDP अनुपालन.",
        "enterEmailToNotify": "अधिकृत अद्यतनांसाठी तुमचा ईमेल प्रविष्ट करा",
        "citizenServices": "नागरी सेवा",
        "product": "वैशिष्ट्ये",
        "trustAndCompliance": "विश्वास आणि अनुपालन",
        "yourChoices": "तुमच्या निवडी",
        "manageCookiePreferences": "कुकी प्राधान्ये व्यवस्थापित करा",
        "consentFramework": "संमती चौकट",
        "cookiePolicy": "कुकी धोरण",
        "privacyPolicy": "गोपनीयता धोरण",
        "accessibility": "सुलभता (Accessibility)",
        "dpdpCompliance": "DPDP अनुपालन",
        "eligibilityChecker": "पात्रता पडताळणी",
        "welfareGapsReport": "सुटलेल्या लाभांचा अहवाल",
        "digilockerVerification": "डिजिलॉकर पडताळणी",
        "whatIfSimulation": "सिम्युलेशन विश्लेषण",
        "interactiveRoadmap": "मार्गदर्शक आराखडा",
        "citizenPortal": "नागरिक पोर्टल",
        "welcomeToSahaya": "टेक सहायामध्ये स्वागत आहे",
        "welcomePortalDesc": "वैयक्तिकृत योजना, कागदपत्रे आणि थेट पात्रता ट्रॅकिंगसाठी सुरक्षित नागरिक प्रवेश.",
        "secureCitizenAccess": "सुरक्षित नागरिक लॉगिन",
        "signInTitle": "टेक सहायामध्ये साइन इन करा",
        "signInSubtitle": "पडताळणी केलेले लाभ आणि कागदपत्रे पाहण्यासाठी तुमचे तपशील भरा.",
        "emailAddressLabel": "ईमेल पत्ता",
        "passwordLabel": "पासवर्ड",
        "rememberMe": "माझी आठवण ठेवा",
        "forgotPasswordLink": "पासवर्ड विसरलात?",
        "continueToVerification": "दोन-टप्प्यांच्या पडताळणीकडे पुढे जा",
        "verifyingSending": "पडताळणी सुरू आहे आणि कोड पाठवला जात आहे...",
        "cybersecurityGate": "सायबर सुरक्षा अखंडता गेट",
        "twoStepVerification": "दोन-टप्प्यांची पडताळणी (2FA)",
        "sentSecurityCode": "आम्ही ६-अंकी सुरक्षा कोड पाठवला आहे:",
        "enter6DigitCode": "६-अंकी कोड टाका",
        "didntReceiveCode": "कोड मिळाला नाही?",
        "resendOtp": "पुन्हा पाठवा (Resend OTP)",
        "verifyAndSignIn": "पडताळणी करा आणि साइन इन करा",
        "verifying": "पडताळणी करत आहे...",
        "backToLogin": "← लॉगिनकडे परत जा",
        "dontHaveAccount": "खाते नाही?",
        "createAccountLink": "खाते तयार करा",
        "autoFillCode": "कोड भरा",
        "securityCodeNotice": "तुमचा ६-अंकी पडताळणी कोड:",
        "securityCodeSent": "अधिकृत सुरक्षा कोड पाठवला आहे"
    },
    "gu": {
        "dpdpAct": "DPDP કાયદો",
        "signIn": "સાઇન ઇન કરો",
        "createAccount": "ખાતું બનાવો",
        "digitalCitizenWelfare": "ડિજિટલ નાગરિક કલ્યાણ પ્લેટફોર્મ",
        "govTechSandbox": "સરકારી ટેક સેન્ડબોક્સ: લાઇવ",
        "deterministic": "ચોક્કસ ગણિતીય પરિણામો",
        "highContrastMode": "હાઇ કોન્ટ્રાસ્ટ (High Contrast)",
        "simpleModeLabel": "સરળ મોડ",
        "footerTagline": "જાહેર સેવા કલ્યાણ પ્લેટફોર્મ",
        "footerDesc": "સમગ્ર ભારતમાં નાગરિકોને ગોપનીયતાની સુરક્ષા સાથે સરકારી કલ્યાણકારી યોજનાઓ પહોંચાડે છે. DPDP કાયદા હેઠળ ડિજિટલ વિશ્વાસ અને સાયબર સુરક્ષા પૂરી પાડે છે.",
        "headquarters": "મુખ્યાલય: રાષ્ટ્રીય માહિતી વિજ્ઞાન કેન્દ્ર (NIC) અને નાગરિક સહાય ડેસ્ક, બેંગલુરુ, ભારત",
        "emailSupportLabel": "ઇમેઇલ સપોર્ટ:",
        "getSchemeNotifications": "યોજના અને નવીનીકરણ સૂચનાઓ મેળવો",
        "notifyMe": "મને જણાવો",
        "zeroSpamGuarantee": "શૂન્ય સ્પામ ગેરંટી. ૧૦૦% સંમતિ આધારિત DPDP પાલન.",
        "enterEmailToNotify": "સત્તાવાર અપડેટ્સ માટે તમારો ઇમેઇલ દાખલ કરો",
        "citizenServices": "નાગરિક સેવાઓ",
        "product": "લક્ષણો",
        "trustAndCompliance": "વિશ્વાસ અને પાલન",
        "yourChoices": "તમારી પસંદગીઓ",
        "manageCookiePreferences": "કૂકી પસંદગીઓ મેનેજ કરો",
        "consentFramework": "સંમતિ માળખું",
        "cookiePolicy": "કૂકી નીતિ",
        "privacyPolicy": "ગોપનીયતા નીતિ",
        "accessibility": "સુલભતા (Accessibility)",
        "dpdpCompliance": "DPDP પાલન",
        "eligibilityChecker": "પાત્રતા તપાસનાર",
        "welfareGapsReport": "બાકી રહેલા લાભોનો અહેવાલ",
        "digilockerVerification": "ડિજીલોકર ચકાસણી",
        "whatIfSimulation": "સિમ્યુલેશન વિશ્લેષણ",
        "interactiveRoadmap": "માર્ગદર્શક રોડમેપ",
        "citizenPortal": "નાગરિક પોર્ટલ",
        "welcomeToSahaya": "ટેક સહાયમાં સ્વાગત છે",
        "welcomePortalDesc": "વ્યક્તિગત યોજનાઓ, દસ્તાવેજો અને રીઅલ-ટાઇમ પાત્રતા ટ્રેકિંગ માટે સુરક્ષિત નાગરિક પ્રવેશ.",
        "secureCitizenAccess": "સુરક્ષિત નાગરિક લૉગિન",
        "signInTitle": "ટેક સહાયમાં સાઇન ઇન કરો",
        "signInSubtitle": "ચકાસાયેલ યોજનાઓ અને દસ્તાવેજો મેળવવા માટે તમારી વિગતો દાખલ કરો.",
        "emailAddressLabel": "ઇમેઇલ સરનામું",
        "passwordLabel": "પાસવર્ડ",
        "rememberMe": "મને યાદ રાખો",
        "forgotPasswordLink": "પાસવર્ડ ભૂલી ગયા છો?",
        "continueToVerification": "દ્વિ-પગલાની ચકાસણી પર આગળ વધો",
        "verifyingSending": "ચકાસણી ચાલુ છે અને કોડ મોકલાઈ રહ્યો છે...",
        "cybersecurityGate": "સાયબર સુરક્ષા અખંડિતતા ગેટ",
        "twoStepVerification": "બે-પગલાની ચકાસણી (2FA)",
        "sentSecurityCode": "અમે ૬-અંકનો સુરક્ષા કોડ મોકલ્યો છે:",
        "enter6DigitCode": "૬-અંકનો કોડ દાખલ કરો",
        "didntReceiveCode": "કોડ નથી મળ્યો?",
        "resendOtp": "ફરીથી મોકલો (Resend OTP)",
        "verifyAndSignIn": "ચકાસો અને સાઇન ઇન કરો",
        "verifying": "ચકાસી રહ્યું છે...",
        "backToLogin": "← લૉગિન પર પાછા જાઓ",
        "dontHaveAccount": "ખાતું નથી?",
        "createAccountLink": "ખાતું બનાવો",
        "autoFillCode": "કોડ ભરો",
        "securityCodeNotice": "તમારો ૬-અંકનો ચકાસણી કોડ:",
        "securityCodeSent": "સત્તાવાર સુરક્ષા કોડ મોકલ્યો છે"
    }
}

with open("frontend/src/utils/i18n.ts", "r", encoding="utf-8") as f:
    text = f.read()

for lang_code, keys in all_translations.items():
    # Find the end of docGenericSample line in that language
    # Example in kn: docGenericSample: "ಸಾಮಾನ್ಯ ಮಾದರಿ ದಾಖಲೆ (Generic Document)"
    # We will insert the new keys after that line
    pattern = rf'(\s+docGenericSample:\s*"[^"]*")(\s*\n  \}},?\s*\n  (?:te|ta|ml|bn|mr|gu|\}} as const;))'
    
    # Generate formatted lines
    lines = []
    for k, v in keys.items():
        v_escaped = v.replace("\"", "\\\"")
        lines.append(f'    {k}: "{v_escaped}",')
    formatted_block = ",\n" + "\n".join(lines)
    
    # We locate the specific block for lang_code
    lang_start = text.find(f"  {lang_code}: {{")
    if lang_start == -1:
        print(f"Error: {lang_code} not found")
        continue
    
    # Find the next closing bracket for this language
    # search for docGenericSample after lang_start
    doc_pos = text.find("docGenericSample:", lang_start)
    if doc_pos == -1:
        print(f"Error: docGenericSample not found in {lang_code}")
        continue
    # find the newline after this line
    nl_pos = text.find("\n", doc_pos)
    # Check if there is already a comma
    prev_line = text[doc_pos:nl_pos].rstrip()
    if not prev_line.endswith(","):
        # add comma
        insert_text = ",\n" + "\n".join(lines)
    else:
        insert_text = "\n" + "\n".join(lines)
    
    text = text[:nl_pos] + insert_text + text[nl_pos:]
    print(f"Added {len(keys)} keys to {lang_code}")

with open("frontend/src/utils/i18n.ts", "w", encoding="utf-8") as f:
    f.write(text)

print("SUCCESS: Updated i18n.ts")
